function: mzi_lattice_mmi
info: {}
module: gdsfactory.components.mzi_lattice
name: mzi_lattice_mmi
settings:
  coupler_gaps_mmis:
  - 0.25
  - 0.25
  coupler_lengths_mmis:
  - 5.5
  - 5.5
  coupler_lengths_tapers:
  - 10.0
  - 10.0
  coupler_widths:
  - null
  - null
  coupler_widths_mmis:
  - 2.5
  - 2.5
  coupler_widths_tapers:
  - 1.0
  - 1.0
  cross_sections_mmis:
  - xs_sc
  - xs_sc
  delta_lengths:
  - 10.0
  mzi:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      combiner:
        function: mmi2x2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
  splitter:
    function: mmi2x2
  taper_functions_mmis:
  - function: taper
  - function: taper
